//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Evaluator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV_Evaluator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.01	-1.778E-7
        ///0.007	-1.085E-7
        ///0.024	-6.513E-8
        ///0.042	-4.006E-8
        ///0.059	-7.655E-9
        ///0.076	1.453E-8
        ///0.094	2.331E-8
        ///0.111	5.096E-8
        ///0.128	6.494E-8
        ///0.146	7.05E-8
        ///0.163	8.642E-8
        ///0.18	1.023E-7
        ///0.198	1.019E-7
        ///0.215	1.19E-7
        ///0.232	1.334E-7
        ///0.25	1.326E-7
        ///0.267	1.42E-7
        ///0.285	1.57E-7
        ///0.302	1.532E-7
        ///0.319	1.658E-7
        ///0.337	1.768E-7
        ///0.354	1.709E-7
        ///0.371	1.802E-7
        ///0.389	1.92E-7
        ///0.406	1.897E-7
        ///0.423	1.954E-7
        ///0.441	2.063E-7
        ///0.458	2.074E-7
        ///0.475	2.275E-7
        ///0.493	2.528E-7
        ///0.51	2.867E-7
        ///0.527	3.579E-7
        ///0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
    }
}
