//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Evaluator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV_Evaluator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10                       -1                       0.1                      0                        -1	10                       -1                       0.1                      0                        3.722190475363885E-20
        ///10                       -1                       0.1                      0.01                     -0.9990000000000001	10                       -1                       0.1                      0.01                     7.070000000000236E-8
        ///10                       -1                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -2.469054994939116	 2.2221574701714566
        ///-2.242057479373064	 2.2203784927767387
        ///-2.05423427291967	 2.211069533478513
        ///-1.8193724503880009	 2.2170659141796776
        ///-1.5688924332116676	 2.2151029046406787
        ///-1.3184492224641908	 2.205303192957702
        ///-1.130552403153084	 2.2116676379474285
        ///-0.9113087752660798	 2.2256234088887528
        ///-0.6604606938011841	 2.302027420789498
        ///-0.4565776155568506	 2.3787994969788055
        ///-0.2839677330307029	 2.4636536515044636
        ///-0.15835966015397362	 2.5410391681747075
        ///-0.04840658835076539	 2.618 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatsudaDelta {
            get {
                return ResourceManager.GetString("MatsudaDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -4.35184896695422	0.790814558058925
        ///-3.8883658208868	0.790814558058925
        ///-3.48387143886433	0.790814558058925
        ///-3.04568379646759	0.790814558058925
        ///-2.7254444725722	0.790814558058925
        ///-2.48948941639242	0.790814558058925
        ///-2.08499503436995	0.790814558058925
        ///-1.66364671976321	0.790814558058925
        ///-1.36027593324635	0.790814558058925
        ///-1.25913773294647	0.791681109185442
        ///-1.17485346523085	0.792547660311958
        ///-1.0905399879267	0.795147313691508
        ///-0.997784939536152	0.798613518197574
        ///-0.921869218935603	0.802946273830 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatsudaK {
            get {
                return ResourceManager.GetString("MatsudaK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.9095203643018	-4.22626292718219
        ///19.7801421458058	-4.19408860705622
        ///19.6184193726859	-4.15387070689875
        ///19.3920926075669	-4.10548155083628
        ///19.2142401157594	-4.06519981274205
        ///18.9879133506405	-4.01681065667958
        ///18.7615865855215	-3.9684215006171
        ///18.5998638124016	-3.92820360045963
        ///18.3574073285951	-3.8797506064604
        ///18.1148657275397	-3.82338170830319
        ///17.8238498531727	-3.75890539217772
        ///17.5975230880538	-3.71051623611525
        ///17.4035408775588	-3.67017066008426
        ///17.1609992765034	-3.61380176192705
        ///16.9508022 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatsudaXi {
            get {
                return ResourceManager.GetString("MatsudaXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.2576735757163	-4.4771397289237
        ///17.9622833843016	-4.4028391286292
        ///17.7161248914561	-4.3409219617172
        ///17.4576207195982	-4.2728319552989
        ///16.8544946577565	-4.1180579152038
        ///16.5959904858986	-4.0499679087855
        ///16.0668629893909	-3.9260769434063
        ///15.8328991580775	-3.8580246913581
        ///15.5005474383659	-3.7713595348662
        ///15.1805413976667	-3.6908672178805
        ///14.8358439989428	-3.5980292218825
        ///14.4419904103899	-3.4989617548232
        ///14.0972930116660	-3.4061237588252
        ///13.7281307811378	-3.3194019707782
        ///13.3588175331294	-3.22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatsudaXi06 {
            get {
                return ResourceManager.GetString("MatsudaXi06", resourceCulture);
            }
        }
    }
}
